#!/bin/bash

pip install .

find . ! -path ./binder ! -path './binder/*' -delete

nbgrader quickstart example_course

mkdir example_course_exchange

chmod ugo+rw example_course_exchange

echo 'c = get_config()' > nbgrader_config.py
echo 'c.CourseDirectory.root = "./example_course"' >> nbgrader_config.py
echo 'c.Exchange.root = "./example_course_exchange"' >> nbgrader_config.py
